# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/suttida/Optcon1.0_cmade

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/suttida/Optcon1.0_cmade

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/suttida/Optcon1.0_cmade/CMakeFiles /home/suttida/Optcon1.0_cmade/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/suttida/Optcon1.0_cmade/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named driver1

# Build rule for target.
driver1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 driver1
.PHONY : driver1

# fast build rule for target.
driver1/fast:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/build
.PHONY : driver1/fast

#=============================================================================
# Target rules for targets named driver2

# Build rule for target.
driver2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 driver2
.PHONY : driver2

# fast build rule for target.
driver2/fast:
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/build
.PHONY : driver2/fast

#=============================================================================
# Target rules for targets named suttida

# Build rule for target.
suttida: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 suttida
.PHONY : suttida

# fast build rule for target.
suttida/fast:
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/build
.PHONY : suttida/fast

cg_descent.o: cg_descent.c.o
.PHONY : cg_descent.o

# target to build an object file
cg_descent.c.o:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/cg_descent.c.o
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/cg_descent.c.o
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/cg_descent.c.o
.PHONY : cg_descent.c.o

cg_descent.i: cg_descent.c.i
.PHONY : cg_descent.i

# target to preprocess a source file
cg_descent.c.i:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/cg_descent.c.i
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/cg_descent.c.i
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/cg_descent.c.i
.PHONY : cg_descent.c.i

cg_descent.s: cg_descent.c.s
.PHONY : cg_descent.s

# target to generate assembly for a file
cg_descent.c.s:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/cg_descent.c.s
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/cg_descent.c.s
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/cg_descent.c.s
.PHONY : cg_descent.c.s

driver1.o: driver1.c.o
.PHONY : driver1.o

# target to build an object file
driver1.c.o:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/driver1.c.o
.PHONY : driver1.c.o

driver1.i: driver1.c.i
.PHONY : driver1.i

# target to preprocess a source file
driver1.c.i:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/driver1.c.i
.PHONY : driver1.c.i

driver1.s: driver1.c.s
.PHONY : driver1.s

# target to generate assembly for a file
driver1.c.s:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/driver1.c.s
.PHONY : driver1.c.s

driver2.o: driver2.c.o
.PHONY : driver2.o

# target to build an object file
driver2.c.o:
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/driver2.c.o
.PHONY : driver2.c.o

driver2.i: driver2.c.i
.PHONY : driver2.i

# target to preprocess a source file
driver2.c.i:
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/driver2.c.i
.PHONY : driver2.c.i

driver2.s: driver2.c.s
.PHONY : driver2.s

# target to generate assembly for a file
driver2.c.s:
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/driver2.c.s
.PHONY : driver2.c.s

optcon.o: optcon.c.o
.PHONY : optcon.o

# target to build an object file
optcon.c.o:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/optcon.c.o
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/optcon.c.o
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/optcon.c.o
.PHONY : optcon.c.o

optcon.i: optcon.c.i
.PHONY : optcon.i

# target to preprocess a source file
optcon.c.i:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/optcon.c.i
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/optcon.c.i
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/optcon.c.i
.PHONY : optcon.c.i

optcon.s: optcon.c.s
.PHONY : optcon.s

# target to generate assembly for a file
optcon.c.s:
	$(MAKE) -f CMakeFiles/driver1.dir/build.make CMakeFiles/driver1.dir/optcon.c.s
	$(MAKE) -f CMakeFiles/driver2.dir/build.make CMakeFiles/driver2.dir/optcon.c.s
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/optcon.c.s
.PHONY : optcon.c.s

suttida.o: suttida.c.o
.PHONY : suttida.o

# target to build an object file
suttida.c.o:
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/suttida.c.o
.PHONY : suttida.c.o

suttida.i: suttida.c.i
.PHONY : suttida.i

# target to preprocess a source file
suttida.c.i:
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/suttida.c.i
.PHONY : suttida.c.i

suttida.s: suttida.c.s
.PHONY : suttida.s

# target to generate assembly for a file
suttida.c.s:
	$(MAKE) -f CMakeFiles/suttida.dir/build.make CMakeFiles/suttida.dir/suttida.c.s
.PHONY : suttida.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... driver1"
	@echo "... driver2"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... suttida"
	@echo "... cg_descent.o"
	@echo "... cg_descent.i"
	@echo "... cg_descent.s"
	@echo "... driver1.o"
	@echo "... driver1.i"
	@echo "... driver1.s"
	@echo "... driver2.o"
	@echo "... driver2.i"
	@echo "... driver2.s"
	@echo "... optcon.o"
	@echo "... optcon.i"
	@echo "... optcon.s"
	@echo "... suttida.o"
	@echo "... suttida.i"
	@echo "... suttida.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

